trigger:
  branches:
    include:
    - '*'
    # - master
    # - releases/*
  paths:
    exclude:
    - README.md
    - CHANGELOG.md

jobs:
  - job: Windows
    pool:
      vmImage: 'windows-latest'

    steps:
    - powershell: | 
        Uninstall-Module Pester -MinimumVersion 5.0.0 -Force
        Install-Module -Name Pester -Force -SkipPublisherCheck -RequiredVersion 4.10.1
        Install-Module -Name ImportExcel -Force -SkipPublisherCheck
        Install-Module -Name SqlServer -Force -SkipPublisherCheck
        
        $r = Invoke-Pester -PassThru
        if($r.FailedCount -gt 0){throw "tests failed"}
      displayName: 'Remove/Install Modules - Run tests'
    # - powershell: './CI/CI.ps1 -Test'
    #   displayName: 'Install and Test'

  - job: WindowsPSCore
    pool:
      vmImage: 'windows-latest'
    steps:
    - pwsh: |    
        gmo -list Pester
        #Uninstall-Module Pester -Verbose
        Uninstall-Module Pester -RequiredVersion 5.0.2 -Force

        # $r=gmo -list pester|select -First 1
        # $r
        # if($r.Version -ge [version]'5.0') {
        #   Uninstall-Module Pester -MinimumVersion 5.0.2 -Force
        # }    
        # Install-Module -Name Pester -Force -SkipPublisherCheck -RequiredVersion 4.10.1
        # Install-Module -Name ImportExcel -Force -SkipPublisherCheck
        # Install-Module -Name SqlServer -Force -SkipPublisherCheck
        
        # $r = Invoke-Pester -PassThru
        # if($r.FailedCount -gt 0){throw "tests failed"}
      displayName: 'Remove/Install Modules - Run tests'

  # - job: WindowsPSCore
  #   pool:
  #     vmImage: 'windows-latest'

  #   steps:
  #   - pwsh: 'Install-Module -Name Pester -Force'
  #     displayName: 'Update Pester'
  #   - pwsh: 'Install-Module -Name ImportExcel -Force -SkipPublisherCheck'
  #     displayName: 'Install ImportExcel'
  #   - pwsh: './CI/CI.ps1 -Test'
  #     displayName: 'Install and Test'

  - job: Ubuntu
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - pwsh: |    
        gmo -list Pester
        Uninstall-Module Pester -Verbose

        # $r=gmo -list pester|select -First 1
        # $r
        # if($r.Version -ge [version]'5.0') {
        #   Uninstall-Module Pester -MinimumVersion ($r.Version.tostring()) -Force
        # }    
        # Install-Module -Name Pester -Force -SkipPublisherCheck -RequiredVersion 4.10.1
        # Install-Module -Name ImportExcel -Force -SkipPublisherCheck
        # Install-Module -Name SqlServer -Force -SkipPublisherCheck
        
        # $r = Invoke-Pester -PassThru
        # if($r.FailedCount -gt 0){throw "tests failed"}
      displayName: 'Remove/Install Modules - Run tests'

  #   steps:
  #   - powershell: 'Install-Module -Name Pester -Force'
  #     displayName: 'Update Pester'
  #   - powershell: 'Install-Module -Name ImportExcel -Force -SkipPublisherCheck'
  #     displayName: 'Install ImportExcel'
  #   - powershell: './CI/CI.ps1 -Test'
  #     displayName: 'Install and Test'

  - job: macOS
    pool:
      vmImage: 'macOS-latest'
    steps:
    - pwsh: |    
        gmo -list Pester
        Uninstall-Module Pester -Verbose

        # $r=gmo -list pester|select -First 1
        # $r
        # if($r.Version -ge [version]'5.0') {
        #   Uninstall-Module Pester -MinimumVersion ($r.Version.tostring()) -Force
        # }    
        # Install-Module -Name Pester -Force -SkipPublisherCheck -RequiredVersion 4.10.1
        # Install-Module -Name ImportExcel -Force -SkipPublisherCheck
        # Install-Module -Name SqlServer -Force -SkipPublisherCheck
        
        # $r = Invoke-Pester -PassThru
        # if($r.FailedCount -gt 0){throw "tests failed"}
      displayName: 'Remove/Install Modules - Run tests'

  #   steps:
  #   - script: brew install mono-libgdiplus
  #     displayName: 'Install mono-libgdiplus'
  #   - powershell: 'Install-Module -Name Pester -Force'
  #     displayName: 'Update Pester'
  #   - powershell: 'Install-Module -Name ImportExcel -Force -SkipPublisherCheck'
  #     displayName: 'Install ImportExcel'
  #   - powershell: './CI/CI.ps1 -Test'
  #     displayName: 'Install and Test'